name: rest_api_client
description: Abstraction for reading and persisting data to platform specific storage.
version: 0.0.1
repository: https://github.com/salihagic/rest_api_client

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1
  storage_repository: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
